### Inleiding

Ik probeer de bacterie tabel(len) te visualiseren.

In [11]:
import numpy as np
import pandas as pd

In [24]:
# Pivot_ZAWZI_Ranked-Table 1

d1 = pd.read_csv('./data/Pivot_ZAWZI_Ranked-Table 1.csv', sep=';', decimal ='.', skiprows=8, header=1)

In [27]:
d1.sample(5)

,Domain,Phylum,Class,Genera,Frequentie,Aantal > -1,Aantal > -2,Max,Min,Difference,...,W,X,Y,Z,ZA,ZB,ZC,ZD,ZE,ZF
414,Bacteria,Proteobacteria,Betaproteobacteria,Candidatus Accumulibacter,21,0,0,"-4,08","-5,11","1,03",...,NaN,"-4,69",NaN,"-4,66",NaN,NaN,NaN,"-4,08",NaN,"-4,75"
1661,Bacteria,Actinobacteria,Actinobacteria,Jatrophihabitans,1,0,0,"-4,96","-4,96","0,00",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1176,Bacteria,Bacteroidetes,Flavobacteriia,Flavivirga,5,0,0,"-4,07","-5,31","1,24",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1725,Bacteria,Firmicutes,Clostridia,Natronincola,1,0,0,"-5,54","-5,54","0,00",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1247,Eukaryota,Opisthokonta,Holozoa,Acari,4,0,0,"-3,67","-5,40","1,74",...,"-4,36",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN