In [25]:
import pandas as pd
import xlwings as xw
pd.set_option('display.max_columns',200)

In [27]:
PATH = 'C:/Users/kleis500/Eclipse workspace/KNN_DS/Waterlaboratorium-Noord-IoT/Data/Kennisnetwerk_data_WWTPpopulaties_WLN.xlsx'
wb = xw.Book(PATH)
sheet = wb.sheets['Pivot_ZAWZI_Ranked']

df1 = sheet['A1:AP2000'].options(pd.DataFrame, index=False, header=False).value

In [28]:
df1.head(15)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41
0,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2,None,None,Max,Maximal Result,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
3,None,None,Min,Minimal Result (Measured!),None,None,None,None,None,Process,WWTP,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
4,None,None,Difference,Max - Min,None,None,None,None,None,Year_Sample,2014,None,None,2015,None,None,None,None,None,None,None,None,None,None,None,None,None,2016,None,None,None,None,None,None,None,None,None,None,None,None,None,2017
5,None,None,Result,Log(Fraction),None,None,None,None,None,Sample,4717_003,4717_008,4717_010,4717_012,4717_013,4717_014,4717_016,4717_018,4717_020,4717_022,4717_024,4717_026,4717_028,4717_030,4717_032,4717_033,4717_035,4717_036,4717_037,4717_038,4717_040,4717_041,4717_042,4717_043,4717_044,4717_047,4717_051,4717_054,4717_058,4717_081,4717_082,4717_083
6,None,None,None,None,None,None,None,None,None,Weeknumber,42,46,51,2,4,10,14,19,22,26,30,34,38,42,46,48,52,3,6,11,15,17,21,23,27,30,34,38,42,47,52,6
7,None,None,None,Total number of samples,32,None,None,None,None,Detectionlevel,-4.85372,-5.41164,-5.52867,-5.32765,-4.45976,-5.23948,-4.54686,-5.13363,-5.12339,-5.29562,-5.29941,-5.1686,-4.36,-4.39411,-5.53907,-5.50899,-5.09385,-5.36961,-5.52634,-4.73084,-5.52798,-5.31388,-5.10983,-5.29105,-4.41061,-5.52249,-4.66759,-4.3317,-4.51747,-5.36699,-4.82456,-5.38203
8,None,None,None,None,None,None,None,None,None,Number_Genera,760,1011,970,924,414,331,348,654,558,855,779,765,503,380,1024,960,685,805,853,284,696,669,826,1001,369,961,590,482,405,943,348,699
9,Domain,Phylum,Class,Genera,Frequentie,Aantal > -1,Aantal > -2,Max,Min,Difference,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
10,Eukaryota,SAR,Alveolata,Cryptocaryon,32,1,10,-0.594352,-5.04537,4.45102,-3.85373,-1.99287,-2.9656,-1.59975,-1.23559,-0.594352,-2.80651,-2.16719,-2.30961,-2.97618,-3.22754,-2.55407,-3.93403,-2.13406,-2.81672,-2.34685,-1.81459,-1.96639,-2.88787,-3.65167,-1.95926,-2.14994,-1.52824,-3.47152,-2.19755,-5.04537,-3.57652,-3.55355,-1.02135,-4.06596,-1.55204,-2.28133
11,Bacteria,Proteobacteria,Deltaproteobacteria,Desulforhopalus,32,0,1,-1.80662,-5.23948,3.43285,-3.32653,-2.60458,-2.29358,-2.6668,-3.17346,-5.23948,-2.75215,-3.02984,-2.19553,-2.12479,-2.3347,-2.48798,-3.36,-3.01391,-2.11274,-2.2295,-3.51028,-2.17345,-2.11733,-3.4521,-2.49244,-2.39938,-3.55758,-2.47549,-2.84242,-1.80662,-2.0399,-3.39385,-3.51748,-2.02941,-3.43246,-2.17721
12,Bacteria,Firmicutes,Clostridia,Abyssivirga,32,0,10,-1.40094,-4.72878,3.32784,-4.72878,-3.92499,-4.03732,-3.53761,-3.34582,-4.31866,-2.49766,-1.81033,-2.24758,-1.64537,-2.07001,-2.60871,-2.31079,-2.49285,-2.03484,-1.98679,-1.86028,-1.68577,-1.40094,-2.92017,-2.43669,-2.08782,-2.1306,-1.92241,-2.24726,-2.05807,-1.95524,-2.19499,-2.70457,-1.75646,-2.0634,-1.89999
13,Bacteria,Proteobacteria,Deltaproteobacteria,Desulfofustis,32,0,11,-1.58898,-4.88798,3.299,-1.70104,-1.58898,-1.70939,-2.15003,-2.27508,-3.47606,-4.02399,-3.91179,-2.92292,-2.06904,-1.75611,-1.60112,-1.8585,-2.35803,-2.59873,-2.65775,-3.40367,-2.55383,-2.92611,-4.42981,-4.21272,-4.29965,-4.88798,-3.58634,-1.70992,-1.97078,-1.88561,-1.77181,-1.85253,-2.04472,-3.1285,-3.49368
14,Bacteria,Proteobacteria,Deltaproteobacteria,Desulfopila,32,0,1,-1.95986,-5.23948,3.27961,-3.49834,-2.60548,-2.39803,-2.77743,-3.24669,-5.23948,-2.86563,-2.83479,-2.18439,-2.36114,-2.47142,-2.4381,-3.37473,-3.25846,-2.30054,-2.36966,-3.30617,-2.24415,-2.33621,-3.19513,-2.63535,-2.5683,-3.24652,-2.52914,-3.22498,-1.95986,-2.25152,-3.4664,-3.69357,-2.31099,-3.46284,-2.48259

In [29]:
df1_part1 = df1.loc[9:,0:9].copy()
df1_part1.columns = df1_part1.iloc[0]
df1_part1.drop(labels = 9, axis = 0, inplace = True)

In [30]:
df1_part1.head()

9,Domain,Phylum,Class,Genera,Frequentie,Aantal > -1,Aantal > -2,Max,Min,Difference
10,Eukaryota,SAR,Alveolata,Cryptocaryon,32,1,10,-0.594352,-5.04537,4.45102
11,Bacteria,Proteobacteria,Deltaproteobacteria,Desulforhopalus,32,0,1,-1.80662,-5.23948,3.43285
12,Bacteria,Firmicutes,Clostridia,Abyssivirga,32,0,10,-1.40094,-4.72878,3.32784
13,Bacteria,Proteobacteria,Deltaproteobacteria,Desulfofustis,32,0,11,-1.58898,-4.88798,3.299
14,Bacteria,Proteobacteria,Deltaproteobacteria,Desulfopila,32,0,1,-1.95986,-5.23948,3.27961

In [31]:
df1_part2 = df1.loc[4:,9:].copy()
df1_part2.drop(labels = [4,6,7,8, 9], axis = 0, inplace = True)

In [18]:
# print(df1_part2.shape)
# df1_part2['index']= list(range(1991))
# df1_part2.head(10)

In [19]:
# cols = list(df1_part2.columns.values)
# cols.insert(1, cols.pop(-1))
# df1_part2 = df1_part2[cols].copy()
df1_part2.columns = df1_part2.iloc[0]
df1_part2.drop(5, axis = 0, inplace = True)
df1_part2 = df1_part2.rename(columns={"Sample": "Difference"}).copy()
# df1_part2.head()

In [20]:
# print(df1_part1.shape)
# print(df1_part2.shape)

In [21]:
df_bac = df1_part1.merge(df1_part2, how='inner', on='Difference')
df_bac.head()

,Domain,Phylum,Class,Genera,Frequentie,Aantal > -1,Aantal > -2,Max,Min,Difference,4717_003,4717_008,4717_010,4717_012,4717_013,4717_014,4717_016,4717_018,4717_020,4717_022,4717_024,4717_026,4717_028,4717_030,4717_032,4717_033,4717_035,4717_036,4717_037,4717_038,4717_040,4717_041,4717_042,4717_043,4717_044,4717_047,4717_051,4717_054,4717_058,4717_081,4717_082,4717_083
0,Eukaryota,SAR,Alveolata,Cryptocaryon,32,1,10,-0.594352,-5.04537,4.45102,-3.85373,-1.99287,-2.9656,-1.59975,-1.23559,-0.594352,-2.80651,-2.16719,-2.30961,-2.97618,-3.22754,-2.55407,-3.93403,-2.13406,-2.81672,-2.34685,-1.81459,-1.96639,-2.88787,-3.65167,-1.95926,-2.14994,-1.52824,-3.47152,-2.19755,-5.04537,-3.57652,-3.55355,-1.02135,-4.06596,-1.55204,-2.28133
1,Bacteria,Proteobacteria,Deltaproteobacteria,Desulforhopalus,32,0,1,-1.80662,-5.23948,3.43285,-3.32653,-2.60458,-2.29358,-2.6668,-3.17346,-5.23948,-2.75215,-3.02984,-2.19553,-2.12479,-2.3347,-2.48798,-3.36,-3.01391,-2.11274,-2.2295,-3.51028,-2.17345,-2.11733,-3.4521,-2.49244,-2.39938,-3.55758,-2.47549,-2.84242,-1.80662,-2.0399,-3.39385,-3.51748,-2.02941,-3.43246,-2.17721
2,Bacteria,Firmicutes,Clostridia,Abyssivirga,32,0,10,-1.40094,-4.72878,3.32784,-4.72878,-3.92499,-4.03732,-3.53761,-3.34582,-4.31866,-2.49766,-1.81033,-2.24758,-1.64537,-2.07001,-2.60871,-2.31079,-2.49285,-2.03484,-1.98679,-1.86028,-1.68577,-1.40094,-2.92017,-2.43669,-2.08782,-2.1306,-1.92241,-2.24726,-2.05807,-1.95524,-2.19499,-2.70457,-1.75646,-2.0634,-1.89999
3,Bacteria,Proteobacteria,Deltaproteobacteria,Desulfofustis,32,0,11,-1.58898,-4.88798,3.299,-1.70104,-1.58898,-1.70939,-2.15003,-2.27508,-3.47606,-4.02399,-3.91179,-2.92292,-2.06904,-1.75611,-1.60112,-1.8585,-2.35803,-2.59873,-2.65775,-3.40367,-2.55383,-2.92611,-4.42981,-4.21272,-4.29965,-4.88798,-3.58634,-1.70992,-1.97078,-1.88561,-1.77181,-1.85253,-2.04472,-3.1285,-3.49368
4,Bacteria,Proteobacteria,Deltaproteobacteria,Desulfopila,32,0,1,-1.95986,-5.23948,3.27961,-3.49834,-2.60548,-2.39803,-2.77743,-3.24669,-5.23948,-2.86563,-2.83479,-2.18439,-2.36114,-2.47142,-2.4381,-3.37473,-3.25846,-2.30054,-2.36966,-3.30617,-2.24415,-2.33621,-3.19513,-2.63535,-2.5683,-3.24652,-2.52914,-3.22498,-1.95986,-2.25152,-3.4664,-3.69357,-2.31099,-3.46284,-2.48259

In [22]:
df_selected = df_bac.loc[df_bac.Difference >= 2.00]
df_selected.Class.unique()
print('This df contains:', len(df_selected.Class.unique()),'different classes of bacteria\nand has the shape', df_selected.shape)

This df contains: 47 different classes of bacteria
and has the shape (408, 42)

In [24]:
df_selected.to_csv(PATH + 'test.csv')